services:
  frontend:
    container_name: frontend
    build: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - pong_network
    ports:
      - "3000:3000"
    restart: always

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - pong_network
    ports:
      - "8080:8080"
    restart: always
  
networks:
  pong_network:
    name: pong_network
    driver: bridge
