services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - pong_network
    ports:
      - "3000:3000"
    restart: always
  
networks:
  pong_network:
    driver: bridge
